name: finapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  currency_text_input_formatter: ^2.1.13
  sqflite: ^2.3.2
  path: ^1.9.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  flex_color_picker: ^3.4.1
  go_router: 15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
  assets:
    - assets/images/svg/
    - assets/images/png/flags/
